[dependencies]
colored = '1.6.1'
either = '1.5.0'
find_folder = '0.3.0'
hound = '3.4.0'
open = '1.2.2'
rayon = '1.0.2'
rustfft = '2.1.0'

[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
name = 'sonny'
version = '0.1.0'
